apiVersion: v1
kind: Secret
metadata:
  name: "secret-{{ include "wise-currency.name" . }}"
data:
  {{- range $key, $value := .Values.secret }}
  {{ $key }}: {{ default "" $value | b64enc }}
  {{- end }}