name: CI wise

on:
  push:
  workflow_dispatch: # Manual trigger


jobs:
  build_image:
    name: Build Docker image
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}}
      - name: Enable build for multiple platform
        run: docker buildx create --driver=docker-container --name=container --use
      - name: Build image amd64 for scanning
        run: docker buildx build --platform linux/amd64 --load -t docker.io/elequiel/wise-currency:${{ github.sha }} .
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'docker.io/elequiel/wise-currency:${{ github.sha }}'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
      - name: Build and push image
        run: docker buildx build --platform linux/amd64,linux/arm64 --push -t docker.io/elequiel/wise-currency:${{ github.sha }} .