name: CI wise

on:
  push:
  workflow_dispatch: # Manual trigger


jobs:
  build_image:
    name: Build Docker image
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}}
      - name: Enable build for multiple platform
        run: docker buildx create --driver=docker-container --name=container --use
      - name: Build image amd64
        run: docker buildx build --platform linux/amd64 --load -t docker.io/elequiel/wise-currency:${{ github.sha }} .
      - name: Create tar file
        run: docker save --output vuln-image.tar docker.io/elequiel/wise-currency:${{ github.sha }}
      - name: Run Trivy vulnerability scanner in tarball mode
        uses: aquasecurity/trivy-action@master
        with:
          input: /github/workspace/vuln-image.tar
          severity: 'CRITICAL,HIGH'