name: CI wise

# on:
#   push:
#     branches:
#         - main
#         - 'realease/**'

# Manual trigger
on: 
 workflow_dispatch:

jobs:
  build_image:
    name: Build Docker image
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}}
      - name: Enable build for multiple platform
        run: docker buildx create --use
      - name: Build image
        run: docker buildx build --platform linux/amd64,linux/arm64 --push -t elequiel/wise-currency:$GITHUB_SHA .
